# Generated by Django 5.2.6 on 2025-09-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=251, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
