# Generated by Django 5.2.6 on 2025-09-24 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_created_at_alter_order_order_number_and_more'),
        ('users', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.address', verbose_name='Адрес доставки'),
        ),
    ]
