# Generated by Django 5.2.6 on 2025-09-26 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_address'),
        ('products', '0007_remove_ingredient_energy_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product'),
        ),
        migrations.DeleteModel(
            name='ItemInShoppingCart',
        ),
    ]
