# Generated by Django 5.2.8 on 2025-11-18 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderitem_price'),
        ('users', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_adress', to='users.address', verbose_name='Адрес доставки'),
        ),
    ]
