# Generated by Django 5.2.8 on 2025-11-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_shoppingcart_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.DateTimeField(blank=True, help_text='Дата доставки', null=True),
        ),
    ]
