# Generated by Django 5.2.8 on 2025-11-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('days_offset', models.PositiveIntegerField()),
                ('delivery_time_from', models.TimeField()),
                ('delivery_time_to', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доставка'),
        ),
    ]
