# Generated by Django 5.2.8 on 2025-11-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_deliveryrule_alter_order_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryrule',
            options={'verbose_name': 'Политика доставки', 'verbose_name_plural': 'Политика доставки'},
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('sbp', 'СБП'), ('cash', 'Наличные курьеру')], default='sbp', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='deliveryrule',
            name='days_offset',
            field=models.PositiveIntegerField(verbose_name='Сдвиг по дням'),
        ),
        migrations.AlterField(
            model_name='deliveryrule',
            name='delivery_time_from',
            field=models.TimeField(verbose_name='Время начала доставки'),
        ),
        migrations.AlterField(
            model_name='deliveryrule',
            name='delivery_time_to',
            field=models.TimeField(verbose_name='Время окончания доставки'),
        ),
        migrations.AlterField(
            model_name='deliveryrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='deliveryrule',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название правила'),
        ),
        migrations.AlterField(
            model_name='deliveryrule',
            name='time_from',
            field=models.TimeField(verbose_name='Начало периода заказа'),
        ),
        migrations.AlterField(
            model_name='deliveryrule',
            name='time_to',
            field=models.TimeField(verbose_name='Конец периода заказа'),
        ),
    ]
