# Generated by Django 5.2.8 on 2025-12-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_deliveryrule_options_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_product_in_order',
        ),
    ]
