# Generated by Django 5.2.8 on 2025-12-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_orderitem_unique_product_in_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCounters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reset_year', models.PositiveBigIntegerField()),
                ('orders_in_year', models.PositiveIntegerField()),
            ],
        ),
    ]
