# Generated by Django 5.2.8 on 2025-12-14 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_ordercounters'),
        ('products', '0020_alter_ingredient_nutrients_alter_product_price'),
        ('users', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='users.address', verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='product_orders', through='orders.OrderItem', to='products.product', verbose_name='Продукты'),
        ),
    ]
