# Generated by Django 5.2.8 on 2026-01-10 20:48

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_address_alter_order_products'),
        ('users', '0006_alter_address_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Стоимость (руб.)')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Варианты доставки',
                'verbose_name_plural': 'Варианты доставки',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Методы оплаты',
                'verbose_name_plural': 'Методы оплаты',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time_from',
            field=models.TimeField(default=datetime.time(10, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time_to',
            field=models.TimeField(default=datetime.time(10, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordercounters',
            name='last_reset_year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_address', to='users.address', verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='deliveryrule',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='orders.delivery', verbose_name='Доставка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(default=datetime.date(2026, 1, 10), on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.delivery', verbose_name='Способ доставки'),
            preserve_default=False,
        ),
    ]
