# Generated by Django 5.2.8 on 2026-01-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_remove_deliveryrule_delivery_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Варианты доставки', 'verbose_name_plural': '_Варианты доставки'},
        ),
        migrations.AlterModelOptions(
            name='deliveryrule',
            options={'verbose_name': 'Политика доставки', 'verbose_name_plural': '_Политика доставки'},
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
