# Generated by Django 5.2.8 on 2026-01-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_delivery_options_alter_deliveryrule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='address',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time_from',
            field=models.TimeField(blank=True, null=True, verbose_name='со времени'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time_to',
            field=models.TimeField(blank=True, null=True, verbose_name='до врмени'),
        ),
    ]
