# Generated by Django 5.2.8 on 2026-01-22 17:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_remove_order_total_price_order_items_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Итого (руб.)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма товаров (руб.)'),
        ),
    ]
