# Generated by Django 5.2.8 on 2026-01-28 12:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_order_total_price_alter_order_items_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='requires_delivery_slot',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Стоимость доставки (руб.)'),
        ),
    ]
