# Generated by Django 5.2.8 on 2026-01-31 08:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Стоимость (руб.)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requires_delivery_slot', models.BooleanField(default=True, verbose_name='Требуется выбор даты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Варианты доставки',
                'verbose_name_plural': '_Варианты доставки',
            },
        ),
        migrations.CreateModel(
            name='DeliveryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название правила')),
                ('time_from', models.TimeField(verbose_name='Начало периода заказа')),
                ('time_to', models.TimeField(verbose_name='Конец периода заказа')),
                ('days_offset', models.PositiveIntegerField(verbose_name='Сдвиг по дням')),
                ('delivery_time_from', models.TimeField(verbose_name='Время начала доставки')),
                ('delivery_time_to', models.TimeField(verbose_name='Время окончания доставки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Политика доставки',
                'verbose_name_plural': '_Политика доставки',
            },
        ),
    ]
