# Generated by Django 5.2.8 on 2026-02-09 10:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('is_available', models.BooleanField(default=True, help_text='Снимите галю, чтобы скрыть категорию.', verbose_name='Доступен')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('proteins', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Белки')),
                ('fats', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Жиры')),
                ('carbs', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Углеводы')),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('measurement_unit', models.CharField(max_length=16, verbose_name='Единица измерения')),
                ('rda', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.0'), help_text='Рекомендуемая суточная потребность', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='РСП')),
            ],
            options={
                'verbose_name': 'нутриент',
                'verbose_name_plural': 'нутриенты',
            },
        ),
        migrations.CreateModel(
            name='IngredientInProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_100g', models.DecimalField(decimal_places=2, help_text='Укажите количество этого ингредиента в граммах', max_digits=6, validators=[django.core.validators.MinValueValidator(0.009)], verbose_name='Количество на 100 г. продукта')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='products.ingredient', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'ингредиент в продукте',
                'verbose_name_plural': 'ингредиенты в продуктах',
            },
        ),
        migrations.CreateModel(
            name='NutrientInIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_100g', models.DecimalField(decimal_places=3, help_text='Количество нутриента на 100 г ингредиента (в граммах)', max_digits=6, validators=[django.core.validators.MinValueValidator(0.0009)], verbose_name='Количество на 100 г. ингредиента')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_links', to='products.ingredient', verbose_name='Ингредиент')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_ingredients', to='products.nutrient', verbose_name='Нутриент')),
            ],
            options={
                'verbose_name': 'нутриент в ингредиенте',
                'verbose_name_plural': 'нутриенты в ингредиентах',
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nutrients',
            field=models.ManyToManyField(help_text='Выберите нутриенты и укажите их количество', related_name='ingredients', through='products.NutrientInIngredient', to='products.nutrient', verbose_name='Нутриент'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('nutrition_mode', models.CharField(choices=[('none', 'Без БЖУ'), ('auto', 'Рассчитать из ингредиентов'), ('manual', 'Ввести вручную')], default='none', max_length=10, verbose_name='БЖУ')),
                ('proteins', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Белки')),
                ('fats', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Жиры')),
                ('carbs', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Углеводы')),
                ('energy_value', models.PositiveIntegerField(blank=True, default=0, help_text='Энергетическая ценность продукта, ккал', null=True, verbose_name='Энергетическая ценность, ккал')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('weight', models.FloatField(default=0, help_text='Вес (гр.)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес')),
                ('is_available', models.BooleanField(default=True, help_text='Снимите галю, чтобы скрыть товар.', verbose_name='Доступен')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Цена, руб.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.009'))], verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Категория')),
                ('ingredients', models.ManyToManyField(help_text='Выберите ингредиенты и укажите их количество', through='products.IngredientInProduct', to='products.ingredient', verbose_name='Ингредиенты')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.AddField(
            model_name='ingredientinproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ingredients', to='products.product', verbose_name='Продукт'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'Изображения продуктов',
                'ordering': ('order',),
            },
        ),
        migrations.AddConstraint(
            model_name='nutrientiningredient',
            constraint=models.UniqueConstraint(fields=('nutrient', 'ingredient'), name='unique_ingredient_in_nutrient'),
        ),
        migrations.AddConstraint(
            model_name='ingredientinproduct',
            constraint=models.UniqueConstraint(fields=('product', 'ingredient'), name='unique_ingredient_in_product'),
        ),
    ]
