# Generated by Django 5.2.11 on 2026-02-20 07:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Разрешены только буквы, цифры, дефисы и подчеркивания. Должен быть уникальным.', unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='ingredientinproduct',
            name='amount_per_100g',
            field=models.DecimalField(decimal_places=2, help_text='Укажите количество этого ингредиента в граммах', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Количество на 100 г. продукта'),
        ),
        migrations.AlterField(
            model_name='nutrientiningredient',
            name='amount_per_100g',
            field=models.DecimalField(decimal_places=3, help_text='Количество нутриента на 100 г ингредиента (в граммах)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество на 100 г. ингредиента'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Цена, руб.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена'),
        ),
    ]
