# Generated by Django 5.2.6 on 2025-09-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Снимите галю, чтобы скрыть скрыть категорию.', verbose_name='Доступен'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Снимите галю, чтобы скрыть товар.', verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Фото'),
        ),
    ]
