# Generated by Django 5.2.6 on 2025-09-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_is_available_product_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, help_text='Вес продукта (граммы)', null=True),
        ),
    ]
