# Generated by Django 5.2.6 on 2025-09-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='carbs',
            field=models.FloatField(default=0, verbose_name='Углеводы'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fats',
            field=models.FloatField(default=0, verbose_name='Жиры'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='proteins',
            field=models.FloatField(default=0, verbose_name='Белки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, help_text='Вес (гр.)', null=True),
        ),
    ]
