# Generated by Django 5.2.6 on 2025-09-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_ingredient_carbs_ingredient_fats_ingredient_proteins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrient',
            name='rda',
            field=models.FloatField(blank=True, help_text='Рекомендуемая суточная потребность', null=True, verbose_name='РСП'),
        ),
    ]
