# Generated by Django 5.2.6 on 2025-09-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_nutrient_rda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='energy_value',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='nutrients',
            field=models.ManyToManyField(help_text='Выберите нутриенты и укажите их количество', through='products.NutrientInIngredient', to='products.nutrient', verbose_name='Нутриент'),
        ),
    ]
