# Generated by Django 5.2.6 on 2025-09-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_ingredient_energy_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carbs',
            field=models.FloatField(default=0, verbose_name='Углеводы'),
        ),
        migrations.AddField(
            model_name='product',
            name='fats',
            field=models.FloatField(default=0, verbose_name='Жиры'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_mode',
            field=models.CharField(choices=[('none', 'Без БЖУ'), ('auto', 'Рассчитать из ингредиентов'), ('manual', 'Ввести вручную')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.FloatField(default=0, verbose_name='Белки'),
        ),
    ]
