# Generated by Django 5.2.6 on 2025-09-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_carbs_product_fats_product_nutrition_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='energy_value',
            field=models.PositiveIntegerField(editable=False, help_text='Энергетическая ценность продукта, ккал', verbose_name='Энергетическая ценность'),
        ),
    ]
