# Generated by Django 5.2.6 on 2025-09-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_energy_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Снимите галю, чтобы скрыть категорию.', verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbs',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='energy_value',
            field=models.PositiveIntegerField(blank=True, help_text='Энергетическая ценность продукта, ккал', null=True, verbose_name='Энергетическая ценность, ккал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Белки'),
        ),
    ]
