# Generated by Django 5.2.6 on 2025-10-12 15:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_is_available_alter_product_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbs',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fats',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='proteins',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Белки'),
        ),
        migrations.AlterField(
            model_name='ingredientinproduct',
            name='amount',
            field=models.DecimalField(decimal_places=1, help_text='Укажите количество этого ингредиента в граммах', max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Количество на 100 г.'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='nutrientiningredient',
            name='amount_per_100g',
            field=models.DecimalField(decimal_places=1, help_text='Количество нутриента на 100 г ингредиента (в граммах)', max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbs',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='energy_value',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Энергетическая ценность продукта, ккал', null=True, verbose_name='Энергетическая ценность, ккал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutrition_mode',
            field=models.CharField(choices=[('none', 'Без БЖУ'), ('auto', 'Рассчитать из ингредиентов'), ('manual', 'Ввести вручную')], default='none', max_length=10, verbose_name='БЖУ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Цена, руб.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.009)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Белки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, default=0, help_text='Вес (гр.)', null=True, verbose_name='Вес'),
        ),
    ]
