# Generated by Django 5.2.6 on 2025-10-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_category_name_alter_ingredient_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0, help_text='Вес (гр.)', verbose_name='Вес'),
        ),
    ]
