# Generated by Django 5.2.6 on 2025-10-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='rda',
            field=models.FloatField(blank=True, default=0, help_text='Рекомендуемая суточная потребность', verbose_name='РСП'),
        ),
    ]
