# Generated by Django 5.2.6 on 2025-10-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_nutrient_rda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='rda',
            field=models.FloatField(blank=True, help_text='Рекомендуемая суточная потребность', null=True, verbose_name='РСП'),
        ),
    ]
