# Generated by Django 5.2.6 on 2025-10-30 15:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_nutrient_rda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='rda',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.0'), help_text='Рекомендуемая суточная потребность', max_digits=6, null=True, verbose_name='РСП'),
        ),
        migrations.AlterField(
            model_name='nutrientiningredient',
            name='amount_per_100g',
            field=models.DecimalField(decimal_places=3, help_text='Количество нутриента на 100 г ингредиента (в граммах)', max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Количество на 100 г.'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
