# Generated by Django 5.2.6 on 2025-10-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_image_alter_nutrient_rda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
