# Generated by Django 5.2.6 on 2025-11-12 11:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_productimage_image_alter_productimage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('order',), 'verbose_name': 'Изображение продукта', 'verbose_name_plural': 'Изображения продуктов'},
        ),
        migrations.AlterField(
            model_name='ingredientinproduct',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Укажите количество этого ингредиента в граммах', max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Количество на 100 г.'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='rda',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.0'), help_text='Рекомендуемая суточная потребность', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='РСП'),
        ),
        migrations.AlterField(
            model_name='nutrientiningredient',
            name='amount_per_100g',
            field=models.DecimalField(decimal_places=3, help_text='Количество нутриента на 100 г ингредиента (в граммах)', max_digits=6, validators=[django.core.validators.MinValueValidator(0.0009)], verbose_name='Количество на 100 г.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0, help_text='Вес (гр.)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
