# Generated by Django 5.2.8 on 2025-11-21 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinproduct',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Укажите количество этого ингредиента в граммах', max_digits=6, validators=[django.core.validators.MinValueValidator(0.009)], verbose_name='Количество на 100 г.'),
        ),
    ]
