# Generated by Django 5.2.8 on 2025-12-14 15:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_ingredientinproduct_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='nutrients',
            field=models.ManyToManyField(help_text='Выберите нутриенты и укажите их количество', related_name='ingredients', through='products.NutrientInIngredient', to='products.nutrient', verbose_name='Нутриент'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Цена, руб.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.009'))], verbose_name='Цена'),
        ),
    ]
