# Generated by Django 5.2.8 on 2025-12-19 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_ingredient_nutrients_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientinproduct',
            name='amount',
        ),
        migrations.AddField(
            model_name='ingredientinproduct',
            name='amount_per_100g',
            field=models.DecimalField(decimal_places=2, default=7, help_text='Укажите количество этого ингредиента в граммах', max_digits=6, validators=[django.core.validators.MinValueValidator(0.009)], verbose_name='Количество на 100 г. продукта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nutrientiningredient',
            name='amount_per_100g',
            field=models.DecimalField(decimal_places=3, help_text='Количество нутриента на 100 г ингредиента (в граммах)', max_digits=6, validators=[django.core.validators.MinValueValidator(0.0009)], verbose_name='Количество на 100 г. ингредиента'),
        ),
    ]
