# Generated by Django 5.2.6 on 2025-09-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
