# Generated by Django 5.2.8 on 2026-01-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('id',), 'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
    ]
